### PR TITLE
Add ext types

### PR DESCRIPTION
**Pull request by sschaef**

### CODE REVIEW

**Comment by sschaef** [comment]
Checks can't pass since new dependency is not yet available

**Comment by vito-c** [comment]
+1 @xuwei-k any plans to merge these PRs?

**Comment by vito-c** [comment]
@xuwei-k can you please provide feedback or some plans to merge?

**Comment by xuwei-k** [comment]
https://github.com/msgpack4z/msgpack4z-api/pull/2 is still not perfect. `msgpack4z-java07` depends on `msgpack4z-api`

**Pull request closed without merging**
